### ISSUE TITLE
TypeError: Cannot read property 'customInspect' of undefined？why？

### ISSUE THREAD

**Issue by zhanggenyuan** [fuse-box/fuse-box-npm-package-seed#2]
^

TypeError: Cannot read property 'customInspect' of undefined
    at Object.<anonymous> (..\fuse-box-npm-package-seed\node_modules\fuse-box\node_modules\fliplog\modules\inspector-gadget\index.js:9:39)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (..\fuse-box-npm-package-seed\node_modules\fuse-box\node_modules\fliplog\plugins\inspect.js:1:75)
    at Module._compile (module.js:541:32)

**Comment by nchanged** [comment]
Please, your config, and the offending line. But before that:

1) Clear the cache (remove `.fuse-box` folder

**Comment by zhanggenyuan** [comment]
i try  ,thanks

**Comment by zhanggenyuan** [comment]
when i run cnpm  cache clean ,but it's invalid .

**Comment by nchanged** [comment]
Sorry? you need to remove '.fuse-box' folder.

**Comment by zhanggenyuan** [comment]
thanks

**Comment by jpike88** [comment]
@nchanged this needs to be reopened, having this issue as well on a fresh build image, node 6.3.1 using the fusebox/es6 module. Fliplog seems to have a problem here.

**Comment by jpike88** [comment]
```
  custom = util.inspect.defaultOptions.customInspect
                                      ^

TypeError: Cannot read property 'customInspect' of undefined
    at Object.<anonymous> (/Users/joshua/Projects/plantguard/client/node_modules/fliplog/modules/inspector-gadget/index.js:9:39)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/joshua/Projects/plantguard/client/node_modules/fliplog/plugins/inspect.js:1:75)
    at Module._compile (module.js:541:32)
```

**Comment by jpike88** [comment]
installing a moden version of node on the build server as a workaround
